# Generated by Django 3.0.1 on 2020-01-13 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artists',
            new_name='artist',
        ),
    ]
